config/routes.rb
Rails.application.routes.draw do

  resources :qr_codes, only: :index do
    collection do
      get :export_to_pdf
      get :download_report
    end
  end
  root 'qr_codes#index'

  resources :download_reports, only: :index

end

app/models/qr_code_pdf_report.rb
class QrCodePdfReport < ActiveRecord::Base

  # Variables
  COMPLETED = 'COMPLETED'
  PENDING = 'PENDING'

  has_attached_file :pdf_file
  validates_attachment_content_type :pdf_file,
    content_type: ['application/pdf'],
    url: "/controllers/:style/:basename.:extension",
    path: ":rails_root/private/pdf_report/:basename.:extension"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/download_reports_controller.rb
class DownloadReportsController < ApplicationController

  def index
    @pdf_reports = QrCodePdfReport.all
  end
end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController

	def index
		params[:page] ||= 1
		offset = (params[:page].to_i - 1) * 24
    api_url = "https://fedex.quickbase.com/db/bmbtc9fjh?a=API_DoQuery&query={6.LT.'1000'}"
		api_url_with_limit = api_url + "&options=num-24.nosort.skp-#{offset}"
    count_api_url = "https://fedex.quickbase.com/db/bmbtc9fjh?a=API_DoQueryCount&query={6.LT.'1000'}"
		token = 'b26njx_9gj_dt9cz7jd4kpymgcq8anydqwjxw7'
		@response = RestClient.post api_url_with_limit + '&usertoken=' + token ,
	            :content_type => :xml
	      response_count = RestClient.post count_api_url + '&usertoken=' + token ,
	            :content_type => :xml
    doc_count = Nokogiri::XML.parse(response_count)
    @total_count = doc_count.xpath("/qdbapi").xpath('numMatches').children.text.to_i
    @total_pages = @total_count/24 + 1 if (@total_count % 24) > 0
		doc = Nokogiri::XML.parse(@response)
		@qr_codes = doc.xpath("/qdbapi/record")
		@kaminari_ary = Kaminari.paginate_array(@qr_codes).page(params[:page]).per(24)
	end

	def export_to_pdf
		api_url = "https://fedex.quickbase.com/db/bmbtc9fjh?a=API_DoQuery&query={6.LT.'1000'}"
		pdf_report_record = find_pdf_report_record(api_url)
		if pdf_report_record.status == QrCodePdfReport::COMPLETED
			@url = download_report_qr_codes_path(id: pdf_report_record.id)
			render_path = 'qr_codes/download_report.js.erb'
		else
			PdfGenerator.new(total_count: params[:total_count], api_url: api_url,
										pdf_report_id: pdf_report_record.id).generate_pdf
			render_path = 'qr_codes/export_to_pdf.js.erb'
		end
		respond_to do |format|
			format.js { render render_path}
		end
	end

	def download_report
		pdf_report = QrCodePdfReport.find(params[:id])
		send_file pdf_report.pdf_file.path, :type => pdf_report.pdf_file_content_type, :disposition => 'inline'
	end

	private

	def find_pdf_report_record(api_url)
		report_obj = QrCodePdfReport.where(total_count: params[:total_count], api_url: api_url,
													status: QrCodePdfReport::COMPLETED).first
		if report_obj
			report_obj
		else
			QrCodePdfReport.create(total_count: params[:total_count], api_url: api_url,
														status: QrCodePdfReport::PENDING)
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/download_reports_helper.rb
module DownloadReportsHelper

  def display_file_name(report)
    if report.status == QrCodePdfReport::COMPLETED
      report.pdf_file_file_name
    else
      ''
    end
  end

  def display_file_type(report)
    if report.status == QrCodePdfReport::COMPLETED
      report.pdf_file_content_type
    else
      ''
    end
  end
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/views/download_reports/index.html.erb
<%= link_to 'Back', root_path %>

<div class="listing_qrcodes">
  <table class="table-fill">
      <thead>
          <tr>
          <th class="text-left"> api_url</th>
          <th class="text-left"> status</th>
          <th class="text-left"> pdf_file_file_name</th>
          <th class="text-left"> pdf_file_content_type</th>
          <th class="text-left"> DOWLOAD</th>
          </tr>
      </thead>
      <tbody class="table-hover">
        <% @pdf_reports.each do |report| %>
          <tr>
              <td class="text-left"><%= report.api_url.split('/')[-1] %></td>
              <td class="text-left"><%= report.status %></td>
              <td class="text-left"><%= display_file_name(report)%></td>
              <td class="text-left"><%= display_file_type(report)%></td>
              <td class="text-left">
                <% if report.status == QrCodePdfReport::COMPLETED %>
                  <%= link_to 'Download', download_report_qr_codes_path(id: report.id)%>
                <% end %>
              </td>
          </tr>
        <%end%>
      </tbody>
  </table>
</div>

app/views/layouts/_css_styles.html.erb
<style>
@media print{
  .content-box{
    page-break-inside: avoid!important;
  }

  .content-box{
  	float: left;
  	display: inline;
  	height: 150px;
  }

  @font-face {
	font-family: 'Code128';
	src: url('../fonts/Code128.eot');
	src: url('../fonts/Code128.eot?#iefix') format('embedded-opentype'),
	url('../fonts/Code128.woff') format('woff'),
	url('../fonts/Code128.ttf') format('truetype');
	font-weight: normal;
	font-style: normal;
	}

	* {
	margin:0;
	padding:0;
	 -webkit-box-sizing: border-box;
	  -moz-box-sizing: border-box;
	  box-sizing: border-box;
	}

	html {
    margin:0;
    padding:0;
		width:100%;
		height:100%;
    font-family: 'univers_condensedbold'
		-webkit-box-sizing: border-box;
	  -moz-box-sizing: border-box;
	  box-sizing: border-box;
	}

  body {
  		margin:0;
  	padding:0;
  	width:100%;
  		height:100%;
  		background-color:#ffffff;
  	}


	a:link {
		color: #000;
		text-decoration: none;
	}
	a:visited {
		text-decoration: none;
		color: #000;
	}
	a:hover {
		text-decoration: none;
		color: #000;
	}
	a:active {
		text-decoration: none;
		color: #F0F0F0;
	}




	img {
	    max-width: 100%;
	    height: auto;
	    width: auto\9; /* ie8 */
		 border: 0; /* 1 */
	    -ms-interpolation-mode: bicubic;
	}


	iframe {
	    max-width: 100%;
	    height: auto;
	    width: auto\9; /* ie8 */
		 border: 0; /* 1 */
	    -ms-interpolation-mode: bicubic;
	}


	.fedex-main-box-3 {


		overflow:auto;
		background-color:#ffffff;
		/*height: 132px;*/
	  padding: 10px;
	  width: 315px;
	}

	.fedex-barcode-small {

		margin: 0;
	}


	.fedex-barcode-small img {

		width: 94%;
	height: 25px;
	text-align: center;
	}


	.barcode-3-box-header {



		margin:0px auto;
		margin-bottom:14px;



	}

	.gap-3 {

	height:10px;

	}
	.barcode-3-box-header h1 {
		font-size: 20px;
		font-weight:700;
		font-family: 'Roboto Condensed', sans-serif;
		text-align:center;
		color:#000000;


	}


	.barcode-3-box-content {



		margin:0px auto;
		margin-top:3px;


	}

	.barcode-3-box-left {

		float:left;
		width:50%;


	}

	.barcode-3-box-left h5 {

		font-size:15px;
		font-weight:700;
		font-family: 'Oswald', sans-serif;
		text-align:left;
		color:#272525;


	}

	.barcode-3-box-left h6 {

		font-size:10px;
		font-weight:normal;
		font-family: 'Oswald', sans-serif;
		text-align:left;
		color:#272525;


	}

	.barcode-3-box-left h6 strong {

		font-size:10px;
		font-weight:normal;
		font-family: 'Oswald', sans-serif;
		text-align:center;
		color:#272525;
		float:right;


	}


	.barcode-3-box-left h2 {

		font-size:31px;
		font-weight:normal;
		font-family: 'Code128';
		text-align:left;
		color:#272525;


	}

	.barcode-3-box-left h4 {

		font-size:15px;
		font-weight:normal;
		font-family: 'Oswald', sans-serif;
		text-align:center;
		color:#272525;


	}

	.barcode-3-box-left h4 strong {

		margin-left:10px;
		padding:0px 8px;

		font-weight:bold;
		font-family: 'Oswald', sans-serif;
		text-align:right;
		color:#272525;


	}


	.barcode-3-box-left h1 {

		font-size: 38px;
		font-weight:700;
		font-family: 'Oswald', sans-serif;
		text-align: right;
		color:#000000;
		margin-top:0;
		padding-left:15px;


	}

	.barcode-3-box-left h1 sup {

		font-size:24px;
		font-weight:700;
		font-family: 'Oswald', sans-serif;
		text-align:left;
		color:#000000;



	}

	.barcode-3-box-left h3 {

		font-size:14px;
		font-weight:700;
		font-family: 'Oswald', sans-serif;
		text-align:center;
		color:#272525;
		padding-left:20px;
		margin-top: -9px;


	}

	.listing_qrcodes{
	  display: -webkit-flex;
	  -webkit-flex-wrap: wrap;
	  flex-wrap:wrap;
	  display: flex;
	  background-color: #ffffff;
	  width: 100%; padding: 30px 30px
	}
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QrPdf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/qr_codes/_qr_codes_partial.html.erb
<div class="listing_qrcodes">
<% qr_codes.each do |num_value| %>
  <div style="margin:0 auto;" class="content-box">
    <div align="center">

    <div class="fedex-main-box-3">
      <div class="barcode-3-box-header">
        <h1><%= num_value.xpath('retek_description').children.text %></h1>
      </div>
      <div class="barcode-3-box-content">
        <div class="barcode-3-box-left">
          <div class="gap-3"></div>
          <div class="barcode-div">
            <h6><%= num_value.xpath('manufacturer').children.text %></h6>
          </div>
          <div class="barcode-div">
            <div class="barcode-3-box-left fix-heading-1">
              <h6><%= num_value.xpath('retek').children.text %></h6>
            </div>
             <div class="barcode-3-box-left">
               <h6>
                 <strong>
                   <%= num_value.xpath('epro').children.text %>
                 </strong>
               </h6>
             </div>
          </div>
            <div class="barcode-div">
              <div class="barcode-3-box-left">
                <h6><%= num_value.xpath('upc').children.text %></h6>
              </div>
              <div class="barcode-3-box-left fix-heading-2">
                <h6>
                  <strong>
                    <%= num_value.xpath('ims_prod_group').children.text%>
                    <span>&#9633;</span>
                  </strong>
              </h6>
              </div>
            </div>
            <div class="fedex-barcode-small">
              <%= image_tag "http://www.barcode-generator.org/zint/api.php?bc_number=20&bc_data=#{num_value.xpath('upc').children.text}"%>
            </div>
        </div>
        <div class="barcode-3-box-left">
          <h1>
            <sup>$
            </sup><%= num_value.xpath('retail').children.text %>
          </h1>
            <h3>
              <% unless num_value.xpath('unit_retail').children.text.blank? %>
                $<%= num_value.xpath('unit_retail').children.text %>
              <% end %>
            </h3>
        </div>
      </div>
    </div>

  </div>

  </div>
  <% end %>
</div>
<br>

app/views/qr_codes/download_report.js.erb
var url = '<%= raw @url%>';
console.log(url);
window.location.replace(url)

app/views/qr_codes/export_to_pdf.js.erb
alert('The Download process has been started. Please redirect to the downloads page');

app/views/qr_codes/index.html.erb
<!-- <div style=" display: -webkit-flex;
   -webkit-flex-wrap: wrap;
   flex-wrap:wrap;
      display: flex;
      width: 100%;">

  <%= @num%>
  </div>
   -->

<!-- <link rel="stylesheet" href="assets/stylesheets/barcode-3.css" type="text/css"> -->
<!-- <link rel="stylesheet" href="assets/fonts/stylesheet.css" type="text/css"> -->


<%= render 'qr_codes_partial', { qr_codes: @qr_codes } %>

<%=paginate(@kaminari_ary, {total_pages: @total_pages, current_page: params[:page].to_i, per_page: 24})%>

<% if @qr_codes.present? %>
  <div class="float_left">
    <%= link_to "Export", export_to_pdf_qr_codes_path(total_count: @total_count), remote: true %>
  </div>
<% end %>

<div class="float_right">
  <%= link_to "Download Page", download_reports_path %>
</div>


<div id="dialog" class="hide">
  <p> Please find the exported pdf in the dowloads page </p>
</div>